package bg.tu.varna.frontend.utils;

public interface Permissions {

    String MANAGE_USERS = "MANAGE_USERS";
    String MANAGE_READERS = "MANAGE_READERS";
    String VIEW_BOOKS = "VIEW_BOOKS";
    String MANAGE_BOOKS = "MANAGE_BOOKS";
    String BORROW_BOOKS = "BORROW_BOOKS";
    String MANAGE_BORROWS = "MANAGE_BORROWS";
    String VIEW_BORROW_BOOKS = "VIEW_BORROW_BOOKS";
    String VIEW_ALL_BORROW_BOOKS = "VIEW_ALL_BORROW_BOOKS";
    String ADMIN_VIEW_ALL_BORROW_BOOKS = "ADMIN_VIEW_ALL_BORROW_BOOKS";
}
